import Head from "next/head";
import React from "react";
import { Footer } from "@/pages/footer";
import Headre from "@/pages/Headre";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>NETFLIX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     <Headre/>
        {children}
        <Footer />
      </main>
    </>
  );
};

export default Layout;
